// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu_QCL3BJ8LcDdg5WRBX1gDovm-IWEdLA',
    appId: '1:469429303747:web:a3fb5884e967db3a672576',
    messagingSenderId: '469429303747',
    projectId: 'videoplayer-4e94e',
    authDomain: 'videoplayer-4e94e.firebaseapp.com',
    storageBucket: 'videoplayer-4e94e.appspot.com',
    measurementId: 'G-BK2WPZ1VVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHoxIfiKzFbLoUfMuJXA5L65h6JuzjEU',
    appId: '1:469429303747:android:5a963e16ed196796672576',
    messagingSenderId: '469429303747',
    projectId: 'videoplayer-4e94e',
    storageBucket: 'videoplayer-4e94e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI09_qP9Kd0EjovlGtry1icSyYwZqhHj0',
    appId: '1:469429303747:ios:7db2d9f4ad8799fd672576',
    messagingSenderId: '469429303747',
    projectId: 'videoplayer-4e94e',
    storageBucket: 'videoplayer-4e94e.appspot.com',
    iosBundleId: 'com.example.videoplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI09_qP9Kd0EjovlGtry1icSyYwZqhHj0',
    appId: '1:469429303747:ios:9ec5c7ffc137bd46672576',
    messagingSenderId: '469429303747',
    projectId: 'videoplayer-4e94e',
    storageBucket: 'videoplayer-4e94e.appspot.com',
    iosBundleId: 'com.example.videoplayer.RunnerTests',
  );
}
